version: "3.8"

services:
  rabbitmq-playground:
    image: "rabbitmq:3.8-management-alpine"
    container_name: rabbitmq-playground
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
