INSERT INTO product_entity (name, price, stock, description) VALUES
('Smartphone XYZ 12', 999.99, '50', 'Smartphone com câmera de 108MP e tela AMOLED de 6.5 polegadas.'),
('Laptop ABC Pro', 2499.99, '30', 'Laptop com processador i7, 16GB RAM e 512GB SSD. Ideal para profissionais.'),
('Fones de Ouvido Bluetooth', 199.99, '100', 'Fones sem fio com cancelamento de ruído e 30 horas de bateria.'),
('Smartwatch Fit 2.0', 299.99, '80', 'Relógio inteligente com monitoramento de saúde e GPS integrado.'),
('Câmera DSLR 24MP', 1499.99, '20', 'Câmera profissional com lente intercambiável e vídeo 4K.'),
('Televisão LED 55"', 2999.99, '15', 'Televisão 4K Ultra HD com Smart TV e controle por voz.'),
('Console de Videogame NextGen', 499.99, '70', 'Console com gráficos de última geração e catálogo de jogos diversificado.'),
('Tablet 10" com Stylus', 399.99, '60', 'Tablet com tela de alta definição e caneta para desenho e anotações.'),
('Micro-ondas Digital 30L', 199.99, '100', 'Micro-ondas com painel digital e funções pré-programadas.'),
('Liquidificador Turbo', 129.99, '120', 'Liquidificador com 5 velocidades e jarra de vidro resistente.'),
('Cafeteira Elétrica Automática', 89.99, '90', 'Cafeteira com capacidade para 12 xícaras e filtro permanente.'),
('Aspirador de Pó Vertical', 159.99, '50', 'Aspirador sem fio com autonomia de 40 minutos e 2 modos de limpeza.'),
('Jogo de Panelas em Aço Inox', 299.99, '40', 'Conjunto de 5 panelas de aço inox com tampa de vidro.'),
('Sofá de Canto Retrátil', 999.99, '25', 'Sofá confortável com função retrátil e revestimento em tecido.'),
('Mesa de Jantar 6 Lugares', 799.99, '30', 'Mesa de madeira maciça com design contemporâneo.'),
('Cadeira de Escritório Ergonômica', 249.99, '50', 'Cadeira ajustável com suporte lombar e rodinhas para fácil movimentação.'),
('Roupão de Banho Adulto', 59.99, '200', 'Roupão de banho em algodão, macio e absorvente.'),
('Tênis Esportivo XYZ', 129.99, '150', 'Tênis com amortecimento e design moderno para corridas.'),
('Relógio Masculino Casual', 89.99, '80', 'Relógio com mostrador analógico e pulseira de couro.'),
('Bolsa de Mão Feminina', 79.99, '100', 'Bolsa em couro sintético, ideal para o dia a dia.'),
('Mochila de Laptop', 69.99, '120', 'Mochila com compartimento acolchoado para laptop e bolsos organizadores.'),
('Camiseta Básica Masculina', 29.99, '300', 'Camiseta de algodão, disponível em várias cores.'),
('Calça Jeans Feminina', 49.99, '200', 'Calça jeans com modelagem slim e lavagem escura.'),
('Perfume Floral Feminino', 59.99, '100', 'Perfume com notas de jasmim e rosa, ideal para uso diário.'),
('Creme Hidratante Corporal', 29.99, '250', 'Creme para hidratação intensa, com fragrância leve.'),
('Escova de Cabelo Profissional', 19.99, '300', 'Escova com cerdas macias, ideal para todos os tipos de cabelo.'),
('Kit de Maquiagem Completo', 99.99, '80', 'Kit com sombras, batons e produtos para a pele.'),
('Lanterna LED Recarregável', 49.99, '60', 'Lanterna potente com diferentes modos de luz e bateria recarregável.'),
('Bicicleta Infantil', 299.99, '25', 'Bicicleta para crianças com design colorido e segurança reforçada.'),
('Carrinho de Bebê Dobrável', 249.99, '20', 'Carrinho leve e fácil de transportar, com reclinação ajustável.'),
('Fralda Descartável Super-Absorvente', 29.99, '150', 'Pacote com 30 unidades, ideal para recém-nascidos.'),
('Roda de Exercícios para Abdômen', 39.99, '100', 'Roda para tonificação abdominal, leve e fácil de usar.'),
('Tábua de Passar Roupa', 89.99, '50', 'Tábua dobrável com altura ajustável e superfície de passar resistente.'),
('Corta-Unhas Profissional', 19.99, '250', 'Corta-unhas com design ergonômico e lâmina afiada.'),
('Sonda de Temperatura Digital', 29.99, '100', 'Sonda digital para medição precisa de temperatura de alimentos.'),
('Bicicleta de Montanha', 499.99, '15', 'Bicicleta robusta para trilhas com suspensão e pneus resistentes.'),
('Saco de Dormir Compacto', 59.99, '60', 'Saco de dormir leve e fácil de transportar, ideal para camping.'),
('Cadeira de Praia Dobrável', 39.99, '80', 'Cadeira leve e compacta, perfeita para viagens e praia.'),
('Hoverboard Elétrico', 499.99, '10', 'Hoverboard com velocidade máxima de 15km/h e bateria de longa duração.'),
('Smart TV 4K 65"', 3499.99, '25', 'Smart TV com tecnologia 4K e assistente de voz integrado.'),
('Estação de Trabalho para Home Office', 199.99, '40', 'Mesa de escritório com design moderno e espaço para organização.'),
('Cafeteira Francesa', 49.99, '100', 'Cafeteira clássica para preparo de café em estilo francês.'),
('Carregador Solar Portátil', 69.99, '80', 'Carregador portátil com painel solar para dispositivos móveis.'),
('Mini Geladeira Portátil', 299.99, '30', 'Geladeira compacta ideal para acampamentos e viagens.'),
('Filtro de Água Refil', 39.99, '200', 'Refil de filtro de água com tecnologia de purificação.'),
('Peixe de Pelúcia Brincalhão', 19.99, '150', 'Brinquedo macio para crianças, ideal para brincar e abraçar.'),
('Triciclo Infantil', 129.99, '25', 'Triciclo seguro e divertido, ideal para crianças pequenas.'),
('Smart Speaker com Assistente Virtual', 199.99, '50', 'Caixa de som inteligente com controle por voz.'),
('Câmara de Segurança Wi-Fi', 149.99, '40', 'Câmera de segurança com visão noturna e detecção de movimento.'),
('Carro Elétrico para Crianças', 699.99, '10', 'Carro elétrico para crianças com controle remoto e design realista.'),
('Lâmpada LED Inteligente', 29.99, '300', 'Lâmpada que pode ser controlada por aplicativo de smartphone.'),
('Organizador de Sapatos', 49.99, '100', 'Organizador de sapatos empilhável, ideal para economizar espaço.'),
('Bicicleta Elétrica', 1999.99, '20', 'Bicicleta com motor elétrico, ideal para trajetos urbanos.'),
('Mini Projetor Portátil', 399.99, '15', 'Projetor compacto com qualidade de imagem HD.'),
('Teclado Mecânico RGB', 149.99, '80', 'Teclado mecânico com retroiluminação RGB, ideal para gamers.'),
('Mouse Gamer Sem Fio', 99.99, '100', 'Mouse gamer ergonômico com alta precisão e design moderno.'),
('Kit de Jardinagem', 59.99, '150', 'Kit completo para jardinagem com ferramentas e luvas.'),
('Globo Terrestre Interativo', 79.99, '50', 'Globo que interage com aplicativos educacionais.'),
('Rádio Portátil com Bluetooth', 69.99, '100', 'Rádio leve com conexão Bluetooth e entrada USB.'),
('Sistema de Som Bluetooth', 299.99, '20', 'Sistema de som potente com conectividade Bluetooth e entradas auxiliares.'),
('Suporte para Laptop', 39.99, '200', 'Suporte ajustável para laptop, ergonômico e portátil.'),
('Capa para Notebook', 29.99, '150', 'Capa protetora para notebooks, disponível em várias cores.'),
('Cachecol de Inverno', 19.99, '200', 'Cachecol de lã macio e aquecido, ideal para o inverno.'),
('Cesta de Piquenique', 59.99, '70', 'Cesta de piquenique com talheres e compartimentos para alimentos.'),
('Protetor Solar FPS 50', 29.99, '150', 'Protetor solar com alta proteção e fórmula resistente à água.'),
('Máscara Facial Hidratante', 19.99, '300', 'Máscara facial com ingredientes naturais para hidratação intensa.'),
('Garrafa Térmica de Aço', 39.99, '100', 'Garrafa térmica com capacidade de 500ml, ideal para bebidas quentes e frias.'),
('Bola de Futebol', 29.99, '200', 'Bola de futebol de couro sintético, ideal para jogos em campo.'),
('Raquete de Tênis', 89.99, '100', 'Raquete leve e resistente, ideal para iniciantes e jogadores intermediários.'),
('Bolsa de Viagem Grande', 79.99, '80', 'Bolsa de viagem com compartimento principal espaçoso e vários bolsos.'),
('Jaqueta Impermeável', 99.99, '50', 'Jaqueta leve e impermeável, ideal para atividades ao ar livre.'),
('Travesseiro Ortopédico', 49.99, '150', 'Travesseiro com design ergonômico para suporte adequado.'),
('Óculos de Sol Estilosos', 59.99, '100', 'Óculos de sol com proteção UV e design moderno.');
